version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
